Repository European-XFEL/EXtra-data, pull requests merged in 2021-11, with the labels that each got.

#236 Only merge in open_run(..., data='all') if raw is not a subset of proc
  extra_data/reader.py
Labels: bug

#234 Fix get_array() when introducing gaps in multi-module detector data
  extra_data/components.py
  extra_data/tests/conftest.py
  extra_data/tests/make_examples.py
  extra_data/tests/test_components.py
Labels: bug

#238 Add release notes for 1.8.1
  docs/changelog.rst
Labels: documentation

#226 Expose public KeyData.train_id_coordinates() method
  docs/reading_files.rst
  extra_data/keydata.py
Labels: enhancement

#242 Updating examples in documentation
  .github/workflows/tests.yml
  docs/aligning_trains.ipynb
  docs/index.rst
  docs/inspection.ipynb
  docs/lpd_data.ipynb
  docs/reading_files.rst
  docs/xpd_examples.ipynb
  docs/xpd_examples2.ipynb
  pytest.ini
Labels: documentation

#228 A robust way to retrieve reduced key values
  docs/reading_files.rst
  extra_data/exceptions.py
  extra_data/keydata.py
  extra_data/tests/test_keydata.py
Labels: enhancement

#249 Add repr for DataCollection objects
  extra_data/reader.py
Labels: enhancement

#248 Avoid scanning keys when making selection
  extra_data/file_access.py
  extra_data/read_machinery.py
  extra_data/reader.py
Labels: enhancement

#225 Skip chunks from files with no trains
  extra_data/keydata.py
  extra_data/tests/test_keydata.py
Labels: bug

#252 Prepare release notes for version 1.9
  docs/changelog.rst
  docs/cli.rst
  docs/validation.rst
  setup.py
Labels: documentation

#257 Fix .data_counts(labelled=False) when source doesn't have some trains
  .github/dependabot/constraints.txt
  extra_data/keydata.py
  extra_data/tests/test_keydata.py
Labels: bug

#258 Add release notes for 1.9.1
  docs/changelog.rst
Labels: documentation
