Repository European-XFEL/EXtra-data, pull requests merged in 2021-01, with the labels that each got.

#98 FIX: Components Dask array dtype
  extra_data/components.py
  extra_data/tests/test_components.py
Labels: bug

#101 Allow retrieving big detector data with cell IDs in the index instead of pulse IDs
  extra_data/components.py
  extra_data/tests/mockdata/detectors.py
  extra_data/tests/test_components.py
Labels: enhancement

#114 Accept DataCollection and KeyData for source selection
  extra_data/reader.py
  extra_data/tests/test_keydata.py
  extra_data/tests/test_reader_mockdata.py
Labels: enhancement

#122 LPD parallel gain
  docs/lpd_data.ipynb
  extra_data/components.py
  extra_data/tests/conftest.py
  extra_data/tests/make_examples.py
  extra_data/tests/test_components.py
Labels: enhancement

#113 Add support to match trains for selected sources/keys
  extra_data/reader.py
  extra_data/tests/test_reader_mockdata.py
Labels: enhancement

#96 DOC: KeyData object
  docs/index.rst
  docs/reading_files.rst
  extra_data/__init__.py
  extra_data/keydata.py
  extra_data/reader.py
Labels: documentation

#130 Try a <= constraint on scipy version in tests
  .github/dependabot/constraints.txt
Labels: testing

#128 Fix select's dict API and broadening of keys by re-selecting
  extra_data/reader.py
  extra_data/tests/test_reader_mockdata.py
Labels: bug
