Repository European-XFEL/EXtra-data, pull requests merged in 2025-03, with the labels that each got.

#604 Fix getting pulse/cell_id_coordinates for XTDF data with pulse selection
  extra_data/components.py
  extra_data/tests/test_components.py
Labels: bug

#606 Fix default value of `skip` when calling validate from cli
  extra_data/validation.py
Labels: bug

#609 Prepare to release 1.21
  README.md
  docs/changelog.rst
  docs/index.rst
  extra_data/__init__.py
Labels: documentation

#612 Feat: trainid selection by bool
  docs/reading_files.rst
  extra_data/read_machinery.py
  extra_data/reader.py
  extra_data/sourcedata.py
  extra_data/tests/test_read_machinery.py
  extra_data/utils.py
Labels: enhancement
