Repository European-XFEL/EXtra-data, pull requests merged in 2025-02, with the labels that each got.

#592 Add units to xarray's attributes
  extra_data/keydata.py
  extra_data/tests/test_keydata.py
Labels: enhancement

#600 Exclude length 0 chunks from VDSs in virtual overview files
  extra_data/writer.py
Labels: bug

#603 Prepare to release 1.20
  docs/changelog.rst
  extra_data/__init__.py
Labels: documentation

#593 Parallel decompression for detector data
  .coveragerc
  .github/workflows/tests.yml
  .readthedocs.yml
  extra_data/components.py
  extra_data/compression.py
  extra_data/keydata.py
  extra_data/tests/make_examples.py
  extra_data/tests/mockdata/detectors.py
  extra_data/tests/test_components.py
  extra_data/tests/test_compression.py
  extra_data/utils.py
  setup.py
Labels: enhancement
