Repository European-XFEL/EXtra-data, pull requests merged in 2025-04, with the labels that each got.

#620 Add reference labels for each release in changelog
  docs/changelog.rst
  docs/conf.py
Labels: documentation

#619 Add support for custom error messages in SourceNameError
  extra_data/exceptions.py
Labels: enhancement

#616 Exclude object arrays for streaming karabo-bridge data
  extra_data/export.py
Labels: bug

#624 Close newly written virtual overview file before renaming it
  extra_data/voview.py
  extra_data/writer.py
Labels: bug
